### ISSUE TITLE
Line Numbers are HUGE!

### ISSUE THREAD

**Issue by iammerrick** [fileability/chocolat-public#1685]

**Comment by yankcrime** [comment]
+1 on this issue - I've got this problem with a trial installation of Chocolat 3.1.2 on my rMBP connected to a (non-Retina) external monitor.  It happens if I launch Chocolat after I connect this monitor.

**Comment by yankcrime** [comment]
Bit of an update - I've noticed that if I launch Chocolat on my external (non-retina) monitor, then the line numbers are huge.  If I launch it first on my rMBP's screen then it's fine.

**Comment by fileability** [comment]
OK I think I've figured out what is going on (and I didn't even have to buy [this £15 piece of plastic](http://store.apple.com/uk/product/M9321G/B/apple-mini-dvi-to-dvi-adapter)!)

It all hinges on my misunderstanding of what `+[NSScreen mainScreen]` does. I was assuming that it means the internal screen, which is why this bug made no sense. The internal screen's retinaness never changes, so if +mainScreen _was_ the internal screen, it would look just fine.

But it occurred to me that if you plugged in an external display, the main screen could change to the external display, and then when you unplugged it it could change back to the internal display.

So I guess the fix for this is to check if *any* screen is a retina display.

**Comment by pketh** [comment]
When I use a retina iMac with a non-retina display I get the opposite - tiny numbers. It sounds like the proposed fix will probably address this case too.

**Comment by fileability** [comment]
So I've attempted to fix this in 3.1.3 which is out today. If anybody here could test it I'd be grateful.

If it's still broken I guess I'll have to fork out that £15 ;)

**Comment by frozzare** [comment]
3.1.3 works for me! Good work @fileability :smile:

**Comment by bazscott** [comment]
Yep 3.1.3 looks good to me too. Plugging, unplugging, restarting Chocolat, every combination I can think of. Thanks \o/

**Comment by yankcrime** [comment]
Happy to confirm that this works for me also.

**Comment by locks** [comment]
:dancers:
